
services:
  backend:
    image: syedrayees/backend:${TAG}
    container_name: backend
    env_file:
      - .env
    expose:
      - "4000"   # internal only
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:4000/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - appnet

  frontend:
    image: syedrayees/frontend:${TAG}
    container_name: frontend
    ports:
      - "80:80"         # ONLY public exposure
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - appnet

networks:
  appnet:
    driver: bridge
